### ISSUE TITLE
Files are not valid JSON objects

### ISSUE THREAD

**Issue by munrocape** [cobalt-uoft/datasets#2]
As it stands, it appears that the files are line-separated JSON objects.

I believe if you were to attempt to consume them with a standard library (open the file, read JSON), it would crash.

Perhaps a standardized format could be implemented:

``` javascript
[obj_1, obj_2, ...]
```

or 

``` javascript
{
    "set_type": "food",
    "version": 1,
    "data": [obj_1, obj_2, ...]
}
```

Including a version number could be helpful if there are breaking changes to what a DB dump may entail.

**Comment by qasim** [comment]
We use [`mongoexport`](https://docs.mongodb.org/manual/reference/program/mongoimport/) and [`mongoimport`](https://docs.mongodb.org/manual/reference/program/mongoimport/) for data dumps.

We can use the `--jsonArray` flag to format `mongoexport` to output as `[obj_1, obj_2, ...]`. This flag is also available for `mongoimport`, however file sizes are limited to 16MB (I'm guessing there's some sort of overhead of having to load the entire array before operating on it, versus reading the current format line by line and importing).

You are right that it isn't valid JSON by itself, but we use tools like [ramda-cli](https://github.com/raine/ramda-cli) and [jq](https://github.com/stedolan/jq) throughout our pipeline to clean up the dumps and perform some level of organization (i.e. ordering, etc.), which take each line of the dumps as standard input as a JSON object to perform operations on. Making the dumps an array would make things harder to work with, since some of the datasets are big and all of it would have to be loaded into memory at once.

**Comment by munrocape** [comment]
Ah cool. I tried just pulling and playing around with them - didn't know there was some Mongo steps required.

I suppose a short README should be added to describe that preferred procedure to consume them?

**Comment by qasim** [comment]
The README is a good idea, some info on how the data is collected + tips on how to utilize it.

I think it's also worth noting that I'm looking at this from a software developer's perspective. I'd love to know how a statistician or someone of the likes would use this sort of data to perform analyses, and if it's possible to cater to them as well.
